### ISSUE TITLE
Questions on the structure of the table entry of SepHash

### ISSUE THREAD

**Issue by JxLi0921** [minxinhao/SepHash#1]
Hello! I have read through the paper and the codebase, it's really an awesome work. But I have a question on the structure of the hash table entry(in the code, it's `struct SEPHASH::Slot`)

As described in the original paper(also in the code), the entry of SepHash has the following structure: 
```cpp
struct Slot
{
    uint8_t fp : 8;
    uint8_t len : 3;
    uint8_t sign : 1;
    uint8_t dep : 4;
    uint64_t offset : 48;
    uint8_t fp_2
} 
```

In my understanding, the design of the table entry tends to keep the slot small(9bytes) while reducing the cost of reading unnecessary kv pairs through adding more fingerprint bits(the `fp2`). 

However, due to the appearance of uint64_t in the definition of the table entry in the code, it seems that `sizeof(Slot)` is actually 16 instead of 9. After I make a minor change on the definition of the struct to make it really 9 bytes, the code cannot run properly mainly because a 9-byte table entry seems not compatible with RDMA-Atomic. Although we only need to apply RDMA-CAS in the first 8 bytes of the table entry, a 9-byte table entry seems break the 8-byte memory alignment of most table entries, which is a requirement of performing RDMA Atomic operations.

My question is that, Is table entry intentionally designed to be 16 bytes? If not, how to use RDMA CAS while using a 9 bytes table entry?

**Comment by minxinhao** [comment]
Thank you for your question, and I apologize for not noticing it earlier.

I also noticed this issue while writing the code previously. In cases where the address is not aligned to 8 bytes, this can be resolved by using the CAS_MASK approach. However, switching to the 4.X version of the RDMA driver is required. To avoid the hassle of switching drivers, I kept the current structure unchanged.

**Comment by JxLi0921** [comment]
Got it, thanks for your reply!
